### ISSUE TITLE
Is dependency Guava required in starter?

### ISSUE THREAD

**Issue by Riggs333** [resteasy/resteasy-spring-boot#133]
The **resteasy-spring-boot-starter** `pom.xml` declares a dependency to **Guava**:
https://github.com/resteasy/resteasy-spring-boot/blob/2d2929777b859c46f4415ce5cd759e923e86f2c5/resteasy-spring-boot-starter/pom.xml#L426-L430

Right now Guava will be packaged as a **transitive dependency** for any project using the starter.

I wonder if Guava is required for the starter or can be removed.
As a test I removed the Guava dependency from the starter's `pom.xml` and haven't noticed any issues when running `mvn verify`.

Can you clarify why Guava is declared here?
Thanks!

**Comment by liweinan** [comment]
@Riggs333 I made a dep-tree analysis and here is the output:

- https://gist.github.com/liweinan/ddbc614828edcc3a693151df31552377

As you can see several components use `guava` as dependencies, and they are using `guava` in different scopes:

- compile
- test
- runtime

So I did a cleanup to the dependencies and mark the `guava`  as `test` scope. The result is that all the tests passed. So let's keep it as `test` scope to see if works.

**Comment by liweinan** [comment]
keep the issue open for a while.
