### ISSUE TITLE
Update Spring Boot to 2.7.3 and Jackson to 2.13.3

### ISSUE THREAD

**Issue by jamezp** [resteasy/resteasy-spring-boot#182]
For the 4.9.x branch of the Spring Boot starter, we are having some Jackson issues when pulling this dependency along Spring Boot 2.7.x. A version of this starter compatible with Spring Boot 2.7.x will be useful. I created a PR in GitHub with some progress (https://github.com/resteasy/resteasy-spring-boot/pull/181)

Migrated from: https://issues.redhat.com/browse/RESTEASY-3206

**Comment by jamezp** [comment]
This currently cannot be done because RESTEasy itself cannot upgrade due to https://github.com/FasterXML/jackson-modules-base/issues/175.

**Comment by jamezp** [comment]
Just as an FYI this has been merged and released in RESTEasy 6.2.0.Beta1 with a RESTEasy 6.2.0.Final being prepared for on 2022-09-22 unless we need it sooner.

**Comment by liweinan** [comment]
@jamezp Can I update Jackson to 2.13.3 now in this project?

**Comment by jamezp** [comment]
@liweinan Only if you upgrade RESTEasy to at least 6.2.0.Beta1.

**Comment by liweinan** [comment]
@jamezp Okay! I'll update RESTEasy firstly.

**Comment by jamezp** [comment]
@liweinan Given there are package changes in Jackson, you likely have to do it at the same time.

**Comment by liweinan** [comment]
@jamezp okay!
