### ISSUE TITLE
Spring-boot-starter releases not pushed to maven central repository

### ISSUE THREAD

**Issue by jamezp** [resteasy/resteasy-spring-boot#241]
The latest release according to Github is

[v6.0.2.Final](https://github.com/resteasy/resteasy-spring-boot/releases/tag/6.0.2.Final)

However the latest verison the maven central repoistories know about is: 
[v6.0.0.Alpha2](https://mvnrepository.com/artifact/org.jboss.resteasy/resteasy-spring-boot-starter)

As earlier releases are available in maven, and also the alpha version, I guess this is not intentional.

Migrated from https://issues.redhat.com/browse/RESTEASY-3336

**Comment by jamezp** [comment]
@liweinan Can you have a look at this? It looks like the project may have just been removed or migrated elsewhere.

**Comment by liweinan** [comment]
@jamezp okay!
