### ISSUE TITLE
Failed to register "<class annotated with @Application>" using Spring Boot 3 

### ISSUE THREAD

**Issue by darku77** [resteasy/resteasy-spring-boot#334]
Starting from Spring **3.0.13**  (latest version that worked) Spring introduced: [Avoid duplicated filter registration](https://github.com/spring-projects/spring-boot/pull/33911)

In our projects we use Spring Boot as war and we do not used the embedded tomcat.

The best explanatory comment I found and very related to ours is this: https://github.com/getsentry/sentry-java/issues/3019#issuecomment-1795090063

Looking at the javadoc from https://github.com/resteasy/resteasy-spring-boot/blob/main/servlet/resteasy-servlet-spring-boot-starter/src/main/java/org/jboss/resteasy/springboot/ResteasyApplicationBuilder.java the workaround I found was to exclude from dependencies the following jar 

```
<dependency>
        <groupId>org.jboss.resteasy</groupId>
        <artifactId>resteasy-servlet-spring-boot-starter</artifactId>
        <version>${spring.boot.resteasy.version}</version>
        <exclusions>
            <exclusion>
                <!-- !! VERY IMPORTANT!!! -->
                <!-- Exclude this as long Spring boot is run as war -->
                <groupId>org.jboss.resteasy</groupId>
                <artifactId>resteasy-servlet-initializer</artifactId>
            </exclusion>
        </exclusions>
 </dependency>
```

is there a better way? since for production we use the war, but for quick development we use the embedded tomcat

**Comment by liweinan** [comment]
@darku77 Thanks for finding this! I have marked the `resteasy-servlet-initializer` dependency scope as `provided` in the main branch as it's only used in the javadocs.
